### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by nerdoc** [rodrigoamaral/django-fullcalendar#10]
On my search for django and fullcalendar apps, I found this software, but it is horribly outdated, and seems completely unmaintained. Fullcalendar is not at 1.x but 5.x AT, and the repo was updated last in 2015, this is 6 years ago.
Would you consider to archive this repository, so that if someone finds it accidentally, he/she is not inclined to use it (and waste time)...
Thanks!

**Comment by rodrigoamaral** [comment]
Hi, @nerdoc ! Thanks for taking the time to open this issue. You're right, I totally forgot about this repo. I'm going to archive it now. 

Thank you
