### ISSUE TITLE
PyPI Registration

### ISSUE THREAD

**Issue by chrisspen** [rodrigoamaral/django-fullcalendar#6]
Could you please register this on PyPI so it can be easily installed and versioned with pip?

**Comment by rrreeeyyy** [comment]
:+1:

**Comment by rodrigoamaral** [comment]
Thank you for your interest in the project! For now, I think it is not mature nor complete enough to be available on PyPI, but I will consider this in the future for sure. Thanks for opening this issue :smile:

**Comment by motorahuls** [comment]
please help {% calendar %} gives an error.
